Added player animations and player model to the project
ppolyanskiyy/LNU-Team-Work-2021 pull request #1
Opened 2021-03-23 07:57 UTC by SwaTiK4931

2021-03-23 07:59 UTC, ppolyanskiyy approved these changes

2021-03-27 16:25 UTC, loburyaka commented
Everything is OK.

2021-03-27 16:27 UTC, loburyaka approved these changes
Everything is OK.

2021-03-27 17:33 UTC, ppolyanskiyy requested changes

2021-03-27 17:33 UTC, ppolyanskiyy commented on Assets/Scripts/PlayerMovement.cs
> +    //void Update()
Why this code is commented?

2021-03-27 17:33 UTC, ppolyanskiyy commented on Assets/Scripts/PlayerMovement.cs
> -        if(Input.GetButtonDown("Jump") && isGrounded)
Why do you remove jumping?

2021-03-27 17:45 UTC, SwaTiK4931 commented on Assets/Scripts/PlayerMovement.cs
> +    //void Update()
There are two Update functions commented because I needed to look in them to understand how it works.

2021-03-27 17:47 UTC, SwaTiK4931 commented on Assets/Scripts/PlayerMovement.cs
> -        if(Input.GetButtonDown("Jump") && isGrounded)
I didn't remove jumping, I have just commented it until I begin making jumping animations.

2021-03-27 17:53 UTC, ppolyanskiyy commented on Assets/Scripts/PlayerMovement.cs
> -        if(Input.GetButtonDown("Jump") && isGrounded)
i think we should close this PR for now, until all animations will be done.

2021-03-27 19:28 UTC, ppolyanskiyy approved these changes

2021-03-27 19:30 UTC, merged